prompt:
  needle: "\nThs passkey is: {passkey}\n"
  haystack_dir: "data/PaulGrahamEssays"
  retrieval_question: "What is the passkey?" # We use the Anthropic's retrieval question as the default one
  # image: "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg"  # null or a path to an image
  # image_needle: "<|needle_of_image|>"

context:
  min_len: 1000
  max_len: 32000
  interval: 10
  manually_select_list: null  # null or a list of context lengths to manually select

document_depth:
  min_percent: 10
  max_percent: 90
  interval: 10
  interval_type: "linear"  # "linear", "sigmoid" or null
  manually_select_list: null  # null or a list of document percents to manually select

tokenizer:
  tokenizer_type: "Huggingface"
  model_name: "/mnt/workspace/ckpts/VLMs/Qwen2-VL-7B-Instruct" # Change it to your own model name / HF model path

save_dir: 'prompts_vpixel'
