prompt_dir: '/mnt/workspace/Projects/CS6223/prompts_text_passkey'
save_dir: '/mnt/workspace/Projects/CS6223/pred_text_passkey'

model:
  model_provider: "Huggingface"  # "OpenAI", "Anthropic" or "Huggingface"
  model_name: "/mnt/workspace/ckpts/VLMs/Qwen2-VL-7B-Instruct"